version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      mimic:
        condition: service_started
    networks:
      - braille_network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/sampledb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      # Always use create-drop to recreate schema on startup
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
    restart: on-failure

  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: sampledb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    # Use tmpfs (memory) for PostgreSQL data - data disappears when container stops
    tmpfs:
      - /var/lib/postgresql/data:exec
    networks:
      - braille_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  mimic:
    image: mycroftai/mimic3
    ports:
      - "59125:59125"
    networks:
      - braille_network
    tmpfs:
      - /home/mimic3/.local/share
    environment:
      - HOME=/home/mimic3
    user: "0:0"

networks:
  braille_network:
    driver: bridge

# No persistent volumes defined